// Typed handles for every element the app scripts. A missing id yields null,
// so callers keep their optional chaining.
/** @param {string} id */
const element = (id) => document.getElementById(id);
/** @param {string} id */
const button = (id) => /** @type {HTMLButtonElement} */ (element(id));
/** @param {string} id */
const input = (id) => /** @type {HTMLInputElement} */ (element(id));
/** @param {string} id */
const select = (id) => /** @type {HTMLSelectElement} */ (element(id));
/** @param {string} id */
const canvas = (id) => /** @type {HTMLCanvasElement} */ (element(id));

export const els = {
  status: element("status"),
  runPhase: element("runPhase"),
  bidsAutoInfo: element("bidsAutoInfo"),
  stepImport: button("stepImport"),
  stepQc: button("stepQc"),
  stepRun: button("stepRun"),
  stepEdit: button("stepEdit"),
  fileName: element("fileName"),
  browseSignalBtn: button("browseSignalBtn"),
  uploadLoader: element("uploadLoader"),
  uploadFormatError: element("uploadFormatError"),
  landing: element("landing"),
  workspace: element("workspace"),
  settingsToggleBtn: button("settingsToggleBtn"),
  settingsOverlay: element("settingsOverlay"),
  settingsPanel: element("settingsPanel"),
  start: button("startBtn"),
  progressText: element("progressText"),
  progressBar: element("progressBar"),
  qcGridTabs: element("qcGridTabs"),
  qcSection: element("qcSection"),
  stageQc: element("stageQc"),
  stageRun: element("stageRun"),
  stageEdit: element("stageEdit"),
  emgCanvas: canvas("emgCanvas"),
  qcAutoBtn: button("qcAutoBtn"),
  artifactAddBtn: button("artifactAddBtn"),
  artifactRemoveBtn: button("artifactRemoveBtn"),
  artifactCount: element("artifactCount"),
  muGridSelect: select("muGridSelect"),
  muSelect: select("muSelect"),
  muMeta: element("muMeta"),
  muPulseCanvas: canvas("muPulseCanvas"),
  niter: input("niter"),
  nwindows: input("nwindows"),
  peelOffToggle: button("peelOffToggle"),
  postprocessMode: select("postprocessMode"),
  postprocessModeHint: element("postprocessModeHint"),
  peelOffSettings: element("peelOffSettings"),
  peelOffWindow: input("peelOffWindow"),
  covToggle: button("covToggle"),
  covSettings: element("covSettings"),
  covValue: input("covValue"),
  silToggle: button("silToggle"),
  silSettings: element("silSettings"),
  silValue: input("silValue"),
  bidsSubject: input("bidsSubject"),
  bidsTask: input("bidsTask"),
  bidsSession: input("bidsSession"),
  bidsAcquisition: input("bidsAcquisition"),
  bidsRun: input("bidsRun"),
  bidsMuscleContainer: element("bidsMuscleContainer"),
  bidsPlacementScheme: select("bidsPlacementScheme"),
  bidsPlacementDescription: input("bidsPlacementDescription"),
  bidsPlacementDescRow: element("bidsPlacementDescRow"),
  bidsPowerlineFreq: select("bidsPowerlineFreq"),
  bidsManufacturer: input("bidsManufacturer"),
  bidsDeviceModel: input("bidsDeviceModel"),
  bidsParticipantAge: input("bidsParticipantAge"),
  bidsParticipantSex: select("bidsParticipantSex"),
  bidsParticipantHandedness: select("bidsParticipantHandedness"),
  editStatus: element("editStatus"),
  fsamp: input("fsamp"),
  bidsProject: input("bidsProject"),
  editMuGridSelect: select("editMuGridSelect"),
  editMuSelect: select("editMuSelect"),
  editSaveBtn: button("editSaveBtn"),
  editResetBtn: button("editResetBtn"),
  editPulseCanvas: canvas("editPulseCanvas"),
  editUpdateBtn: button("editUpdateBtn"),
  editPeelOffToggle: button("editPeelOffToggle"),
  editLockSpikesToggle: button("editLockSpikesToggle"),
  editAddBtn: button("editAddBtn"),
  editAddArtifactBtn: button("editAddArtifactBtn"),
  editDeleteSpikeBtn: button("editDeleteSpikeBtn"),
  editOutliersBtn: button("editOutliersBtn"),
  editFlagBtn: button("editFlagBtn"),
  editDuplicateBtn: button("editDuplicateBtn"),
  editDeduplicateBtn: button("editDeduplicateBtn"),
  editUndoBtn: button("editUndoBtn"),
  editDrCanvas: canvas("editDrCanvas"),
  editTimelineCanvas: canvas("editTimelineCanvas"),
  auxCanvas: canvas("auxCanvas"),
  auxSelector: select("auxSelector"),
  duplicatesthresh: input("duplicatesthresh"),
};

/** @typedef {typeof els} Els */
