import { GRID_COLORS } from "../config.js";

// Single source of truth for the edit-slice shape. Used both for the initial
// state below and by resetEditSlice(), so the two can never drift apart.
export function createEditSlice() {
  return {
    file: null,
    filename: "",
    pulseTrains: [],
    originalPulseTrains: [],
    distimes: [],
    originalDistimes: [],
    artifactTimes: [],
    gridNames: [],
    muGridIndex: [],
    fsamp: null,
    totalSamples: 0,
    currentMuGrid: 0,
    currentMu: 0,
    view: null,
    selectionPulse: null,
    selectionDr: null,
    draftSelectionPulse: null,
    draftSelectionDr: null,
    mode: null,
    dirty: false,
    parameters: null,
    flagged: [],
    backup: null,
    bidsRoot: "",
    project: "",
    editSignalToken: "",
    muUids: [],
    editHistory: [],
    bookmarkPosition: null,
    showBookmark: false,
    softwareVersions: null,
  };
}

export const state = {
  file: null,
  uploadToken: null,
  isRunning: false,
  seriesLength: null,
  rois: [],
  previewSeries: [],
  gridNames: [],
  gridSeries: [],
  gridColors: GRID_COLORS,
  parameters: null,
  channelMeans: [],
  coordinates: [],
  discardMasks: [],
  channelTraces: [],
  qcRepresentation: "raw",
  qcWindowLoading: {},
  metadata: {},
  muscle: [],
  currentStage: "qc",
  currentGrid: 0,
  muPulseTrains: [],
  muDistimes: [],
  muGridIndex: [],
  currentMuGrid: 0,
  currentMu: 0,
  runDownloadInFlight: false,
  lastRunDownloadKey: "",
  runView: null,
  muSelectionRange: null,
  roiDraft: null,
  auxSeries: [],
  auxNames: [],
  edit: createEditSlice(),
};
