export const state = {
  file: null,
  uploadToken: null,
  isRunning: false,
  seriesLength: null,
  rois: [],
  previewSeries: [],
  gridNames: [],
  gridSeries: [],
  gridColors: [
    "#ffffff",
    "#f5f5f5",
    "#e8e8e8",
    "#dcdcdc",
    "#3776ab",
    "#ffd43b",
    "#2ca02c",
  ],
  parameters: null,
  channelMeans: [],
  coordinates: [],
  discardMasks: [],
  channelTraces: [],
  qcRepresentation: "raw",
  qcWindowLoading: {},
  metadata: {},
  muscle: [],
  currentStage: "qc",
  currentGrid: 0,
  muPulseTrains: [],
  muDistimes: [],
  muGridIndex: [],
  currentMuGrid: 0,
  currentMu: 0,
  runDownloadInFlight: false,
  lastRunDownloadKey: "",
  runView: null,
  muSelectionRange: null,
  roiDraft: null,
  auxSeries: [],
  auxNames: [],
  edit: {
    file: null,
    filename: "",
    pulseTrains: [],
    originalPulseTrains: [],
    distimes: [],
    originalDistimes: [],
    gridNames: [],
    muGridIndex: [],
    fsamp: null,
    totalSamples: 0,
    currentMuGrid: 0,
    currentMu: 0,
    view: null,
    selectionPulse: null,
    selectionDr: null,
    draftSelectionPulse: null,
    draftSelectionDr: null,
    mode: null,
    dirty: false,
    parameters: null,
    flagged: [],
    backup: null,
    bidsRoot: "",
    editSignalToken: "",
    muUids: [],
    editHistory: [],
  },
};
